/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package enrollmentsystem;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mercy
 */
public class teachersform extends javax.swing.JFrame {
        String filterString = ";";
        String stID;
    /**
     * Creates new form teachersform
     */
    public teachersform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        teachID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        teachName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        teachDept = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        teachAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        teachContact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        teachStatust = new javax.swing.JTextField();
        savebut = new javax.swing.JButton();
        updatebut = new javax.swing.JButton();
        deletebut = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        logicOP1 = new javax.swing.JComboBox<>();
        choose1 = new javax.swing.JComboBox<>();
        idFilter = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        snameFilter = new javax.swing.JTextField();
        enameFilter = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        saddrFilter = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        eaddrFilter = new javax.swing.JTextField();
        choose2 = new javax.swing.JComboBox<>();
        choose3 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        courseFilter = new javax.swing.JTextField();
        choose4 = new javax.swing.JComboBox<>();
        choose5 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        genderFilter = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        yearlvlFilter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Enter Teachers ID:");

        teachID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachIDActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Teachers Name:");

        teachName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachNameActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter Teachers Department:");

        teachDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachDeptActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter Teachers Address:");

        jLabel5.setText("Enter Teachers Contact:");

        teachContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachContactActionPerformed(evt);
            }
        });

        jLabel6.setText("Enter Teachers Status:");

        teachStatust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachStatustActionPerformed(evt);
            }
        });

        savebut.setText("Save");
        savebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebutActionPerformed(evt);
            }
        });

        updatebut.setText("Update");
        updatebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebutActionPerformed(evt);
            }
        });

        deletebut.setText("Delete");
        deletebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebutActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));

        jLabel7.setText("Teacher ID");

        logicOP1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=", "<", ">", "<=", ">=", "<>" }));
        logicOP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logicOP1ActionPerformed(evt);
            }
        });

        choose1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OR", "AND" }));
        choose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose1ActionPerformed(evt);
            }
        });

        idFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idFilterKeyReleased(evt);
            }
        });

        jLabel8.setText("Teacher Name");

        jLabel9.setText("Starts");

        jLabel10.setText("Ends");

        snameFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snameFilterActionPerformed(evt);
            }
        });
        snameFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                snameFilterKeyReleased(evt);
            }
        });

        enameFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                enameFilterKeyReleased(evt);
            }
        });

        jLabel11.setText("Teacher Address");

        jLabel12.setText("Starts");

        saddrFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                saddrFilterKeyReleased(evt);
            }
        });

        jLabel13.setText("Ends");

        eaddrFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eaddrFilterActionPerformed(evt);
            }
        });
        eaddrFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                eaddrFilterKeyReleased(evt);
            }
        });

        choose2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OR", "AND" }));
        choose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose2ActionPerformed(evt);
            }
        });

        choose3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OR", "AND" }));
        choose3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose3ActionPerformed(evt);
            }
        });

        jLabel14.setText("Teacher Dept.");

        courseFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                courseFilterKeyReleased(evt);
            }
        });

        choose4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OR", "AND" }));
        choose4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose4ActionPerformed(evt);
            }
        });

        choose5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OR", "AND" }));
        choose5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose5ActionPerformed(evt);
            }
        });

        jLabel15.setText("Teacher Contact");

        genderFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFilterActionPerformed(evt);
            }
        });
        genderFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                genderFilterKeyReleased(evt);
            }
        });

        jLabel16.setText("Teacher Status");

        yearlvlFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                yearlvlFilterKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logicOP1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(choose1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(idFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(snameFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enameFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(choose2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choose3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choose4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choose5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(courseFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saddrFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yearlvlFilter)
                                            .addComponent(genderFilter))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eaddrFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(logicOP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(snameFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enameFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choose2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(saddrFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eaddrFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choose3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(courseFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choose4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(genderFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choose5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(yearlvlFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Teacher ID", "Teacher Name", "Teacher Department", "Teacher Address", "Teacher Contact", "Teacher Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("File");

        jMenuItem3.setText("Teachers");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Subjects");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(savebut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updatebut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletebut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teachName)
                            .addComponent(teachID)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(teachDept, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teachStatust)
                            .addComponent(teachContact)
                            .addComponent(teachAddress, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(teachID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(teachName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(teachDept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(teachAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(teachContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(teachStatust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(savebut)
                            .addComponent(updatebut)
                            .addComponent(deletebut)))
                    .addComponent(jScrollPane1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowStudRec(){
        DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
        tblmodel.setRowCount(0);
        
    if(!idFilter.getText().equals("")){
        filterString = " WHERE teachID " + logicOP1.getSelectedItem() + idFilter.getText();
        }
        if(!snameFilter.getText().equals("")){
            if(idFilter.getText().equals("")){
                filterString = String.format("WHERE teachName like '%s%%'", snameFilter.getText());
            }else if(!enameFilter.getText().equals("")){
                filterString += String.format(" %s teachName like '%s%%'", choose1.getSelectedItem(), snameFilter.getText());
            }else{
                filterString += String.format(" %s teachName like '%s%%'", choose1.getSelectedItem(), snameFilter.getText());
            }
            //filterString = " WHERE teachName like '" + snameFilter.getText() + "%' ";
        }
        if(!enameFilter.getText().equals("")){
            if(idFilter.getText().equals("") && snameFilter.getText().equals("")){
                filterString = String.format("WHERE teachName like '%%%s'", enameFilter.getText());
            }else if(snameFilter.getText().equals("")){
                filterString += String.format(" %s teachName like '%%%s'", choose1.getSelectedItem(), enameFilter.getText());
            }else if(!snameFilter.getText().equals("") && idFilter.getText().equals("")){
                filterString += String.format(" AND teachName like '$$$s'", enameFilter.getText());
            }else{
                filterString += String.format(" AND teachName like '$$$s'", enameFilter.getText());
            }
            //filterString = " WHERE teachName like '%" + enameFilter.getText() + "' ";
        }
        if(!saddrFilter.getText().equals("")){
            if(idFilter.getText().equals("") && snameFilter.getText().equals("") && enameFilter.getText().equals("")){
                filterString = String.format("WHERE teachAddress like '%s%%'", saddrFilter.getText());
            }else if(!eaddrFilter.getText().equals("")){
                filterString += String.format(" %s teachAddress like '%s%%'", choose2.getSelectedItem(), saddrFilter.getText());
            }else{
                filterString += String.format(" %s teachAddress like '%s%%'", choose2.getSelectedItem(), saddrFilter.getText());
            }
            // = " WHERE teachAddress like '" + saddrFilter.getText() + "%' ";
        }
        if(!eaddrFilter.getText().equals("")){
            if(idFilter.getText().equals("") && snameFilter.getText().equals("") && enameFilter.getText().equals("") && saddrFilter.getText().equals("")){
                filterString = String.format("WHERE teachAddress like '%%%s'", eaddrFilter.getText());
            }else if(saddrFilter.getText().equals("")){
                filterString += String.format(" %s teachAddress like '%%%s'", choose2.getSelectedItem(), eaddrFilter.getText());
            }else if(!saddrFilter.getText().equals("") && idFilter.getText().equals("") && snameFilter.getText().equals("") && enameFilter.getText().equals("")){
                filterString += String.format(" AND teachAddress like '%%%s'", eaddrFilter.getText());
            }else{
                filterString += String.format(" AND teachAddress like '%%%s'", eaddrFilter.getText());
            }
            //filterString = " WHERE teachAddress like '%" + eaddrFilter.getText() + "' ";
        }
        if(!courseFilter.getText().equals("")){
            if(idFilter.getText().equals("") && snameFilter.getText().equals("") && enameFilter.getText().equals("") && saddrFilter.getText().equals("") && eaddrFilter.getText().equals("")){
                filterString = String.format("WHERE teachDept like '%s%%'", courseFilter.getText());
            }else{
                filterString += String.format(" %s teachDept like '%s%%'", choose3.getSelectedItem(), courseFilter.getText());
            }
            //filterString = " WHERE teachDept='" + courseFilter.getText() + "' ";
        }
        if(!genderFilter.getText().equals("")){
            if(idFilter.getText().equals("") && snameFilter.getText().equals("") && enameFilter.getText().equals("") && saddrFilter.getText().equals("") && eaddrFilter.getText().equals("") && courseFilter.getText().equals("")){
                filterString = String.format("WHERE teachContact like '%s%%'", genderFilter.getText());
            }else{
                filterString += String.format(" %s teachContact like '%s%%'", choose4.getSelectedItem(), genderFilter.getText());
            }
            //filterString = " WHERE teachContact='" + genderFilter.getText() + "' ";
        }
        if(!yearlvlFilter.getText().equals("")){
            if(idFilter.getText().equals("") && snameFilter.getText().equals("") && enameFilter.getText().equals("") && saddrFilter.getText().equals("") && eaddrFilter.getText().equals("") && courseFilter.getText().equals("") && genderFilter.getText().equals("")){
                filterString = String.format("WHERE teachStatust like '%s%%'", yearlvlFilter.getText());
            }else{
                filterString += String.format(" %s teachStatust like '%s%%'", choose5.getSelectedItem(), yearlvlFilter.getText());
            }
            //filterString = " WHERE teachStatust='" + yearlvlFilter.getText() + "' ";
        }
         
        DBConnect connector = new DBConnect();
        
        try{
            String query = "SELECT * FROM teachers" + filterString;
            connector.rs = connector.st.executeQuery(query);
                while(connector.rs.next()){
                    String id = connector.rs.getString("teachID");
                    String name = connector.rs.getString("teachName");
                    String address = connector.rs.getString("teachDept");
                    String course = connector.rs.getString("teachAddress");
                    String gender = connector.rs.getString("teachContact");
                    String year = connector.rs.getString("teachStatust");
                    String[] item = {id,name,address,course,gender,year};
                    tblmodel.addRow(item);
                }
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    private void teachNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachNameActionPerformed

    private void teachDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachDeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachDeptActionPerformed

    private void teachContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachContactActionPerformed

    private void deletebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebutActionPerformed
        teachers teach = new teachers();
        teach.DeleteTeachers(filterString);
        ShowStudRec();
    }//GEN-LAST:event_deletebutActionPerformed

    private void savebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebutActionPerformed
        teachers teach = new teachers();
        teach.AddTeachers(Integer.parseInt(teachID.getText()), teachName.getText(), teachDept.getText(), teachAddress.getText(), teachContact.getText(), teachStatust.getText());
        ShowStudRec();
    }//GEN-LAST:event_savebutActionPerformed

    private void updatebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebutActionPerformed
        teachers teach = new teachers();
        teach.UpdateTeachers(Integer.parseInt(teachID.getText()), teachName.getText(), teachDept.getText(), teachAddress.getText(), teachContact.getText(), teachStatust.getText());
        ShowStudRec();
    }//GEN-LAST:event_updatebutActionPerformed

    private void teachIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachIDActionPerformed

    private void teachStatustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachStatustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teachStatustActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void logicOP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logicOP1ActionPerformed
        ShowStudRec();
    }//GEN-LAST:event_logicOP1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ShowStudRec();
    }//GEN-LAST:event_formWindowOpened

    private void choose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose1ActionPerformed
        ShowStudRec();
    }//GEN-LAST:event_choose1ActionPerformed

    private void idFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idFilterKeyReleased
        ShowStudRec();
    }//GEN-LAST:event_idFilterKeyReleased

    private void snameFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snameFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snameFilterActionPerformed

    private void snameFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snameFilterKeyReleased
        ShowStudRec();
    }//GEN-LAST:event_snameFilterKeyReleased

    private void enameFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enameFilterKeyReleased
        ShowStudRec();
    }//GEN-LAST:event_enameFilterKeyReleased

    private void choose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose2ActionPerformed
        ShowStudRec();
    }//GEN-LAST:event_choose2ActionPerformed

    private void choose3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose3ActionPerformed
        ShowStudRec();
    }//GEN-LAST:event_choose3ActionPerformed

    private void choose4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose4ActionPerformed
        ShowStudRec();
    }//GEN-LAST:event_choose4ActionPerformed

    private void choose5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose5ActionPerformed
        ShowStudRec();
    }//GEN-LAST:event_choose5ActionPerformed

    private void saddrFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saddrFilterKeyReleased
        ShowStudRec();
    }//GEN-LAST:event_saddrFilterKeyReleased

    private void eaddrFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eaddrFilterKeyReleased
        ShowStudRec();
    }//GEN-LAST:event_eaddrFilterKeyReleased

    private void courseFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_courseFilterKeyReleased
        ShowStudRec();
    }//GEN-LAST:event_courseFilterKeyReleased

    private void genderFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_genderFilterKeyReleased
        ShowStudRec();
    }//GEN-LAST:event_genderFilterKeyReleased

    private void yearlvlFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearlvlFilterKeyReleased
        ShowStudRec();
    }//GEN-LAST:event_yearlvlFilterKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String name;
        String address;
        String course;
        String gender;
        String year;
        
        int[] selectRow = jTable1.getSelectedRows();
        stID = (String) jTable1.getValueAt(selectRow[0],0);
        teachID.setText(stID);
        name = (String) jTable1.getValueAt(selectRow[0],1);
        teachName.setText(name);
        address = (String) jTable1.getValueAt(selectRow[0],2);
        teachDept.setText(address);
        course = (String) jTable1.getValueAt(selectRow[0],3);
        teachAddress.setText(course);
        gender = (String) jTable1.getValueAt(selectRow[0],4);
        teachContact.setText(gender);
        year = (String) jTable1.getValueAt(selectRow[0],5);
        teachStatust.setText(year);
    }//GEN-LAST:event_jTable1MouseClicked

    private void genderFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFilterActionPerformed

    private void eaddrFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eaddrFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eaddrFilterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teachersform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teachersform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teachersform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teachersform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teachersform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choose1;
    private javax.swing.JComboBox<String> choose2;
    private javax.swing.JComboBox<String> choose3;
    private javax.swing.JComboBox<String> choose4;
    private javax.swing.JComboBox<String> choose5;
    private javax.swing.JTextField courseFilter;
    private javax.swing.JButton deletebut;
    private javax.swing.JTextField eaddrFilter;
    private javax.swing.JTextField enameFilter;
    private javax.swing.JTextField genderFilter;
    private javax.swing.JTextField idFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> logicOP1;
    private javax.swing.JTextField saddrFilter;
    private javax.swing.JButton savebut;
    private javax.swing.JTextField snameFilter;
    private javax.swing.JTextField teachAddress;
    private javax.swing.JTextField teachContact;
    private javax.swing.JTextField teachDept;
    private javax.swing.JTextField teachID;
    private javax.swing.JTextField teachName;
    private javax.swing.JTextField teachStatust;
    private javax.swing.JButton updatebut;
    private javax.swing.JTextField yearlvlFilter;
    // End of variables declaration//GEN-END:variables
}
